/**
 * Purchases API
 * Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
 *
 * The version of the OpenAPI document: 0.1.9
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Purchase } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PurchaseServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;
    

    /**
     * Returns a list of purchases.
     * Optional extended description in CommonMark or HTML.
     */
    getPurchases(extraHttpRequestParams?: any): Observable<Array<Purchase>>;

}
